const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      description2:
        "The Free Shirt is crafted from high-quality materials to provide exceptional comfort. Its versatile design makes it suitable for both casual and semi-formal occasions. This shirt is designed to last, maintaining its shape and color after multiple washes.",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      description2:
        "The Fit Shirt by Adidas combines style and comfort effortlessly. With its modern fit, it enhances your silhouette while ensuring freedom of movement. Perfect for active days or casual outings, this shirt is a must-have in your wardrobe.",
      isFeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
      description2:
        "The Slim Shirt from Raymond offers a sleek and tailored look, ideal for professional settings or formal events. Made from breathable fabric, it ensures you stay cool and comfortable all day long. Its sophisticated design makes it a timeless piece.",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
      description2:
        "Oliver's Golf Pants are designed for both style and performance. Featuring a comfortable fit, they allow for a full range of motion, perfect for the golf course or casual wear. The durable fabric resists wrinkles and maintains a sharp look.",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
      description2:
        "Fit Pants by Zara are known for their contemporary design and exceptional comfort. The slim fit accentuates your legs while providing ample flexibility. These pants are perfect for both work and weekend outings, offering a polished appearance.",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
      description2:
        "Casely's Classic Pants bring a touch of elegance to any outfit. Made with premium materials, they ensure durability and comfort throughout the day. The timeless design makes them suitable for various occasions, from business meetings to casual gatherings.",
    },
  ],
};

export default data;
